import { useState, useEffect } from 'react';
import { apiFetch } from '../api';

const ARTIFACT_META = {
  testStrategy: {
    icon: '🗺️', label: 'Test Strategy', color: '#6366f1', bg: '#eef2ff', border: '#c7d2fe',
    tagline: 'High-level QA approach & scope',
    whatItIs: 'A Test Strategy defines the overall testing philosophy, scope, tools, environments, risk areas, and entry/exit criteria for a project. It answers "HOW will we test?"',
    whatYouGet: ['Scope & objectives', 'Test levels (unit, integration, E2E)', 'Risk & mitigation table', 'Tools & environments', 'Entry / exit criteria', 'Defect management approach'],
    outputFormat: 'Markdown document (.md)',
    framework: 'QA Lead 15+ years — Anti-Hallucination rules enforced',
    tip: 'Try cloning and adjusting for Agile sprints, API-only projects, or security-focused testing.',
  },
  testPlan: {
    icon: '📋', label: 'Test Plan', color: '#0ea5e9', bg: '#f0f9ff', border: '#bae6fd',
    tagline: '13-section formal SPO test plan',
    whatItIs: 'A Test Plan is the detailed, formal document derived from the Test Strategy for a specific release or sprint. It answers "WHAT exactly will we test, and when?"',
    whatYouGet: ['Test objectives & deliverables', 'Feature list & exclusions', 'Test schedule & milestones', 'Resource & responsibility matrix', 'Environment & data requirements', 'Pass/fail criteria', '+ 7 more SPO sections'],
    outputFormat: 'Markdown document (.md)',
    framework: 'SPO 13-section format — TBD for unknowns, never invented',
    tip: 'Customise for your release process — e.g. shorten to 6 sections for small teams, or add a regression section.',
  },
  testCases: {
    icon: '🧪', label: 'Test Cases', color: '#8b5cf6', bg: '#f5f3ff', border: '#ddd6fe',
    tagline: 'Structured positive & negative test cases',
    whatItIs: 'Test Cases are step-by-step scenarios covering positive, negative, boundary, and edge cases, traced directly to requirements.',
    whatYouGet: ['Test Case ID & title', 'Preconditions', 'Step-by-step actions', 'Expected vs actual result', 'Priority & severity', 'Positive + negative scenarios (min 10)', 'Requirement traceability'],
    outputFormat: 'CSV spreadsheet (.csv) + preview table',
    framework: 'Requirement-traced — no invented behavior',
    tip: 'Add domain-specific rules like "always include WCAG 2.2 accessibility checks" or "cover all API status codes".',
  },
  bugReport: {
    icon: '🐛', label: 'Bug Report', color: '#ef4444', bg: '#fff1f2', border: '#fecdd3',
    tagline: 'Vision-based screenshot defect analysis',
    whatItIs: 'A Bug Report is auto-generated by analyzing a screenshot using AI vision. Only visible or directly inferable defects are reported — nothing is invented.',
    whatYouGet: ['Bug ID & title', 'Severity & priority', 'Steps to reproduce', 'Expected vs actual behavior', 'Environment details', 'Screenshot reference'],
    outputFormat: 'Markdown document (.md)',
    framework: 'Vision analysis — only real visible bugs, empty array if none found',
    tip: 'Adjust severity thresholds or add project-specific defect categories to match your bug tracker fields.',
  },
};

export default function TemplatesTab() {
  const [activeType, setActiveType] = useState('testStrategy');
  const [templates, setTemplates] = useState([]);
  const [expanded, setExpanded] = useState(null);
  const [editing, setEditing] = useState(null);
  const [form, setForm] = useState({ name: '', systemPrompt: '' });
  const [saving, setSaving] = useState(false);
  const [fmtOverride, setFmtOverride] = useState({});
  const [error, setError] = useState('');
  const [showGuide, setShowGuide] = useState(true);

  useEffect(() => { loadTemplates(); }, []);

  async function loadTemplates() {
    try { setTemplates(await (await apiFetch('/api/templates')).json()); }
    catch { setError('Failed to load templates'); }
  }

  const meta = ARTIFACT_META[activeType];
  const forType = templates.filter(t => t.artifactType === activeType);

  const DEFAULT_FMT = { testStrategy: 'markdown', testPlan: 'markdown', testCases: 'csv', bugReport: 'markdown' };
  const FORMATS = [
    { value: 'markdown', label: 'Markdown (.md)',              icon: '📝', ext: '.md'   },
    { value: 'html',     label: 'HTML (.html)',                icon: '🌐', ext: '.html' },
    { value: 'txt',      label: 'Plain Text (.txt)',           icon: '📄', ext: '.txt'  },
    { value: 'csv',      label: 'CSV Spreadsheet (.csv)',      icon: '📊', ext: '.csv'  },
    { value: 'json',     label: 'JSON (.json)',                icon: '🔧', ext: '.json' },
    { value: 'pdf',      label: 'PDF (.pdf)',                  icon: '🖨️', ext: '.pdf'  },
    { value: 'docx',     label: 'Word (.docx)',               icon: '📘', ext: '.docx' },
    { value: 'xlsx',     label: 'Excel (.xlsx)',              icon: '📗', ext: '.xlsx' },
  ];

  function startNew() { setEditing('new'); setForm({ name: '', systemPrompt: '', outputFormat: DEFAULT_FMT[activeType] || 'markdown' }); setError(''); }
  function startClone(t) { setEditing('new'); setForm({ name: `${t.name} (copy)`, systemPrompt: t.systemPrompt, outputFormat: t.outputFormat || DEFAULT_FMT[activeType] || 'markdown' }); setError(''); }
  function startEdit(t) { setEditing(t.id); setForm({ name: t.name, systemPrompt: t.systemPrompt, outputFormat: t.outputFormat || DEFAULT_FMT[activeType] || 'markdown' }); setError(''); }
  function cancelEdit() { setEditing(null); setForm({ name: '', systemPrompt: '', outputFormat: 'markdown' }); setError(''); }

  async function saveTemplate() {
    if (!form.name.trim() || !form.systemPrompt.trim()) { setError('Name and system prompt are required'); return; }
    setSaving(true); setError('');
    try {
      if (editing === 'new') {
        await apiFetch('/api/templates', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: form.name, artifactType: activeType, systemPrompt: form.systemPrompt, outputFormat: form.outputFormat }) });
      } else {
        await apiFetch(`/api/templates/${editing}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: form.name, systemPrompt: form.systemPrompt, outputFormat: form.outputFormat }) });
      }
      await loadTemplates(); cancelEdit();
    } catch { setError('Failed to save template'); }
    finally { setSaving(false); }
  }

  async function deleteTemplate(id) {
    if (!confirm('Delete this template?')) return;
    try { await apiFetch(`/api/templates/${id}`, { method: 'DELETE' }); await loadTemplates(); if (expanded === id) setExpanded(null); }
    catch { setError('Failed to delete template'); }
  }

  async function updateFormat(id, fmt) {
    setFmtOverride(p => ({ ...p, [id]: fmt })); // optimistic — show instantly
    try {
      await apiFetch(`/api/templates/${id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ outputFormat: fmt }) });
      await loadTemplates();
    } catch {
      setError('Failed to update output format');
      setFmtOverride(p => { const n = { ...p }; delete n[id]; return n; }); // revert on error
    } finally {
      setFmtOverride(p => { const n = { ...p }; delete n[id]; return n; }); // clear override — server state now authoritative
    }
  }

  return (
    <div style={{ display: 'grid', gridTemplateColumns: '220px 1fr', gap: 24, alignItems: 'start' }}>

      {/* ── Left sidebar: artifact type picker ── */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
        <div style={{ fontSize: 11, fontWeight: 700, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.8px', marginBottom: 4 }}>Artifact Type</div>
        {Object.entries(ARTIFACT_META).map(([key, m]) => {
          const count = templates.filter(t => t.artifactType === key).length;
          const active = activeType === key;
          return (
            <button key={key} onClick={() => { setActiveType(key); setEditing(null); setError(''); setExpanded(null); }}
              style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '10px 14px', borderRadius: 10, border: `2px solid ${active ? m.color : '#e2e8f0'}`, background: active ? m.bg : '#fff', cursor: 'pointer', textAlign: 'left', transition: 'all .15s', boxShadow: active ? `0 0 0 3px ${m.color}22` : 'none' }}>
              <span style={{ fontSize: 20 }}>{m.icon}</span>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 13, fontWeight: 700, color: active ? m.color : '#374151' }}>{m.label}</div>
                <div style={{ fontSize: 11, color: '#94a3b8' }}>{count} template{count !== 1 ? 's' : ''}</div>
              </div>
            </button>
          );
        })}
        <div style={{ marginTop: 8, padding: '12px 14px', background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: 10, fontSize: 12, color: '#64748b', lineHeight: 1.5 }}>
          <div style={{ fontWeight: 700, marginBottom: 4, color: '#374151' }}>How templates work</div>
          Built-in templates ship with the app and cannot be edited. Clone one to make your own. In Generate, pick any template per artifact type.
        </div>
      </div>

      {/* ── Right: main content ── */}
      <div>
        {/* Artifact explainer card */}
        <div style={{ background: '#fff', border: `2px solid ${meta.border}`, borderRadius: 14, padding: '20px 24px', marginBottom: 20, borderLeft: `5px solid ${meta.color}` }}>
          <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 16 }}>
            <div style={{ flex: 1 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 }}>
                <span style={{ fontSize: 28 }}>{meta.icon}</span>
                <div>
                  <div style={{ fontSize: 18, fontWeight: 800, color: meta.color }}>{meta.label}</div>
                  <div style={{ fontSize: 12, color: '#64748b', fontWeight: 500 }}>{meta.tagline}</div>
                </div>
              </div>
              <p style={{ fontSize: 13, color: '#475569', margin: '10px 0 0', lineHeight: 1.65 }}>{meta.whatItIs}</p>
            </div>
            <button onClick={() => setShowGuide(p => !p)}
              style={{ flexShrink: 0, background: meta.bg, border: `1px solid ${meta.border}`, color: meta.color, padding: '5px 12px', borderRadius: 7, cursor: 'pointer', fontSize: 12, fontWeight: 600 }}>
              {showGuide ? 'Hide details ▲' : 'Show details ▼'}
            </button>
          </div>

          {showGuide && (
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 14, marginTop: 16, paddingTop: 16, borderTop: `1px solid ${meta.border}` }}>
              <div>
                <div style={{ fontSize: 11, fontWeight: 700, color: meta.color, textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 8 }}>✅ What you get</div>
                <ul style={{ margin: 0, paddingLeft: 16, fontSize: 12, color: '#475569', lineHeight: 2 }}>
                  {meta.whatYouGet.map((item, i) => <li key={i}>{item}</li>)}
                </ul>
              </div>
              <div>
                <div style={{ fontSize: 11, fontWeight: 700, color: meta.color, textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 8 }}>📁 Output format</div>
                <div style={{ fontSize: 12, color: '#475569', background: meta.bg, padding: '8px 12px', borderRadius: 8, border: `1px solid ${meta.border}`, marginBottom: 10 }}>{meta.outputFormat}</div>
                <div style={{ fontSize: 11, fontWeight: 700, color: meta.color, textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 8 }}>🔬 Framework</div>
                <div style={{ fontSize: 12, color: '#475569', background: meta.bg, padding: '8px 12px', borderRadius: 8, border: `1px solid ${meta.border}` }}>{meta.framework}</div>
              </div>
              <div style={{ background: '#fffbeb', border: '1px solid #fde68a', borderRadius: 10, padding: '12px 14px' }}>
                <div style={{ fontSize: 11, fontWeight: 700, color: '#d97706', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 6 }}>💡 Customisation tip</div>
                <p style={{ fontSize: 12, color: '#78350f', margin: 0, lineHeight: 1.65 }}>{meta.tip}</p>
              </div>
            </div>
          )}
        </div>

        {/* Header row */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 }}>
          <div>
            <div style={{ fontSize: 15, fontWeight: 700, color: '#1e293b' }}>Templates for {meta.label}</div>
            <div style={{ fontSize: 12, color: '#94a3b8', marginTop: 2 }}>Built-in templates are read-only. Clone to customise.</div>
          </div>
          {!editing && (
            <button onClick={startNew}
              style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '9px 18px', background: meta.color, color: '#fff', border: 'none', borderRadius: 8, cursor: 'pointer', fontSize: 13, fontWeight: 700, boxShadow: `0 2px 10px ${meta.color}44` }}>
              + New Template
            </button>
          )}
        </div>

        {error && <div style={{ padding: '10px 14px', background: '#fee2e2', borderRadius: 8, color: '#991b1b', fontSize: 13, marginBottom: 14 }}>{error}</div>}

        {/* Edit / New form */}
        {editing && (
          <div style={{ border: `2px solid ${meta.color}`, borderRadius: 12, padding: 20, marginBottom: 18, background: meta.bg }}>
            <div style={{ fontWeight: 700, marginBottom: 14, color: meta.color, fontSize: 15, display: 'flex', alignItems: 'center', gap: 8 }}>
              {meta.icon} {editing === 'new' ? `Create New ${meta.label} Template` : `Edit Template`}
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 14 }}>
              <div>
                <label style={{ display: 'block', fontSize: 12, fontWeight: 700, color: '#475569', marginBottom: 5, textTransform: 'uppercase', letterSpacing: '0.4px' }}>Template Name *</label>
                <input value={form.name} onChange={e => setForm(p => ({ ...p, name: e.target.value }))}
                  placeholder={`e.g. Agile ${meta.label} — Sprint focus`}
                  style={{ width: '100%', padding: '9px 12px', borderRadius: 7, border: `1.5px solid ${meta.border}`, fontSize: 14, background: '#fff', outline: 'none' }} />
              </div>
              <div>
                <label style={{ display: 'block', fontSize: 12, fontWeight: 700, color: '#475569', marginBottom: 5, textTransform: 'uppercase', letterSpacing: '0.4px' }}>Output Format *</label>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 6 }}>
                  {FORMATS.map(f => (
                    <label key={f.value} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '8px 10px', borderRadius: 7, border: `1.5px solid ${form.outputFormat === f.value ? meta.color : '#e2e8f0'}`, background: form.outputFormat === f.value ? meta.bg : '#fff', cursor: 'pointer', fontSize: 12, fontWeight: form.outputFormat === f.value ? 700 : 400, color: form.outputFormat === f.value ? meta.color : '#64748b', transition: 'all .12s' }}>
                      <input type="radio" name="outputFormat" value={f.value} checked={form.outputFormat === f.value} onChange={e => setForm(p => ({ ...p, outputFormat: e.target.value }))} style={{ display: 'none' }} />
                      <span>{f.icon}</span> {f.label}
                    </label>
                  ))}
                </div>
              </div>
            </div>

            <label style={{ display: 'block', fontSize: 12, fontWeight: 700, color: '#475569', marginBottom: 5, textTransform: 'uppercase', letterSpacing: '0.4px' }}>System Prompt (LLM Instructions) *</label>
            <div style={{ fontSize: 12, color: '#64748b', marginBottom: 8, padding: '10px 12px', background: '#fff7ed', border: '1px solid #fed7aa', borderRadius: 6 }}>
              💬 This is sent to the AI as its persona and rules. Start with <strong>"You are a..."</strong> — specify what to include, what to avoid, and output format. The AI always outputs JSON — your prompt shapes the content.
            </div>
            <textarea value={form.systemPrompt} onChange={e => setForm(p => ({ ...p, systemPrompt: e.target.value }))}
              placeholder={`You are a QA Lead specialised in ${meta.label.toLowerCase()} for Agile teams...\n\nSTRICT RULES:\n- Focus on...\n- Always include...\n- Output ONLY valid JSON.`}
              rows={10}
              style={{ width: '100%', padding: '10px 12px', borderRadius: 7, border: `1.5px solid ${meta.border}`, fontSize: 13, fontFamily: 'monospace', resize: 'vertical', background: '#fff', lineHeight: 1.55, boxSizing: 'border-box' }} />
            <div style={{ display: 'flex', gap: 8, marginTop: 12 }}>
              <button onClick={saveTemplate} disabled={saving}
                style={{ padding: '9px 20px', background: saving ? '#94a3b8' : meta.color, color: '#fff', border: 'none', borderRadius: 7, cursor: 'pointer', fontSize: 13, fontWeight: 700, boxShadow: saving ? 'none' : `0 2px 8px ${meta.color}44` }}>
                {saving ? '⏳ Saving...' : '💾 Save Template'}
              </button>
              <button onClick={cancelEdit}
                style={{ padding: '9px 16px', background: '#fff', color: '#475569', border: '1.5px solid #e2e8f0', borderRadius: 7, cursor: 'pointer', fontSize: 13, fontWeight: 600 }}>
                Cancel
              </button>
            </div>
          </div>
        )}

        {/* Template cards */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {forType.length === 0 && !editing && (
            <div style={{ textAlign: 'center', padding: 48, border: '2px dashed #e2e8f0', borderRadius: 12, background: '#f8fafc' }}>
              <div style={{ fontSize: 40, marginBottom: 12 }}>📭</div>
              <div style={{ fontWeight: 700, color: '#64748b', marginBottom: 6 }}>No templates for {meta.label}</div>
              <div style={{ fontSize: 13, color: '#94a3b8' }}>Click &ldquo;+ New Template&rdquo; to create one.</div>
            </div>
          )}
          {forType.map(t => (
            <div key={t.id} style={{ border: `1.5px solid ${expanded === t.id ? meta.color : '#e2e8f0'}`, borderRadius: 12, overflow: 'hidden', background: '#fff', boxShadow: expanded === t.id ? `0 2px 14px ${meta.color}22` : '0 1px 4px rgba(0,0,0,.04)', transition: 'all .2s' }}>
              {/* Card header */}
              <div style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '14px 18px', cursor: 'pointer', background: expanded === t.id ? meta.bg : '#fff', transition: 'background .15s' }}
                onClick={() => setExpanded(expanded === t.id ? null : t.id)}>
                <div style={{ width: 38, height: 38, borderRadius: 9, background: t.builtIn ? '#e0e7ff' : '#d1fae5', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 20, flexShrink: 0 }}>
                  {t.builtIn ? '🔒' : '✏️'}
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
                    <span style={{ fontWeight: 700, fontSize: 14, color: '#1e293b' }}>{t.name}</span>
                    <span style={{ fontSize: 11, fontWeight: 700, padding: '2px 8px', borderRadius: 10, background: t.builtIn ? '#e0e7ff' : '#d1fae5', color: t.builtIn ? '#3730a3' : '#065f46' }}>
                      {t.builtIn ? '🔒 Built-in' : '✏️ Custom'}
                    </span>
                  </div>
                  <div style={{ fontSize: 12, color: '#64748b', marginTop: 3 }}>
                    {t.builtIn ? 'Read-only — click to preview, Clone to customise' : 'Your custom template — click to preview or Edit'}
                  </div>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: 6 }} onClick={e => e.stopPropagation()}>
                  {/* Inline output format selector — works for all templates */}
                  <select
                    value={fmtOverride[t.id] ?? t.outputFormat ?? DEFAULT_FMT[t.artifactType] ?? 'markdown'}
                    onChange={e => updateFormat(t.id, e.target.value)}
                    title="Select output format"
                    style={{ fontSize: 12, fontWeight: 600, padding: '5px 8px', borderRadius: 6, border: `1.5px solid ${meta.border}`, background: meta.bg, color: meta.color, cursor: 'pointer', minWidth: 160 }}>
                    {FORMATS.map(f => <option key={f.value} value={f.value}>{f.icon} {f.label}</option>)}
                  </select>
                  <button onClick={() => startClone(t)}
                    style={{ padding: '5px 12px', borderRadius: 6, border: '1.5px solid #e2e8f0', background: '#f8fafc', color: '#475569', cursor: 'pointer', fontSize: 12, fontWeight: 600 }}>
                    📋 Clone
                  </button>
                  {!t.builtIn && editing !== t.id && (
                    <button onClick={() => startEdit(t)}
                      style={{ padding: '5px 12px', borderRadius: 6, border: `1.5px solid ${meta.border}`, background: meta.bg, color: meta.color, cursor: 'pointer', fontSize: 12, fontWeight: 600 }}>
                      ✏️ Edit
                    </button>
                  )}
                  {!t.builtIn && (
                    <button onClick={() => deleteTemplate(t.id)}
                      style={{ padding: '5px 12px', borderRadius: 6, border: '1.5px solid #fecaca', background: '#fff1f2', color: '#dc2626', cursor: 'pointer', fontSize: 12, fontWeight: 600 }}>
                      🗑️
                    </button>
                  )}
                </div>
                <div style={{ color: meta.color, fontSize: 18, marginLeft: 4, flexShrink: 0 }}>{expanded === t.id ? '▲' : '▼'}</div>
              </div>

              {/* Expanded: system prompt viewer */}
              {expanded === t.id && (
                <div style={{ padding: '0 18px 18px', borderTop: `1px solid ${meta.border}`, background: meta.bg }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, margin: '14px 0 8px' }}>
                    <span style={{ fontSize: 12, fontWeight: 700, color: meta.color, textTransform: 'uppercase', letterSpacing: '0.5px' }}>System Prompt</span>
                    <span style={{ fontSize: 11, color: '#94a3b8' }}>— the instructions sent to the AI</span>
                  </div>
                  <pre style={{ fontSize: 12.5, background: '#1e1b4b', color: '#c7d2fe', borderRadius: 10, padding: '16px 18px', whiteSpace: 'pre-wrap', wordBreak: 'break-word', margin: 0, lineHeight: 1.75, fontFamily: '"Fira Code", "Cascadia Code", monospace' }}>
                    {t.systemPrompt}
                  </pre>
                  {t.builtIn && (
                    <div style={{ marginTop: 12, padding: '10px 14px', background: '#fffbeb', border: '1px solid #fde68a', borderRadius: 8, fontSize: 12, color: '#92400e', display: 'flex', alignItems: 'center', gap: 8 }}>
                      <span style={{ fontSize: 16 }}>💡</span>
                      <span>Want to customise? Click <strong>Clone</strong> above — edit name + prompt, then use it in Generate by selecting it from the dropdown.</span>
                    </div>
                  )}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
